server:
  port: 8081
  servlet:
    context-path: /community-job

spring:
  application:
    name: community-job
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

mybatis:
  mapper-locations: classpath:com/hidreamai/community/infra/dal/**/*.xml
  type-aliases-package: com.hidreamai.community.infra.dal
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.hidreamai.community: DEBUG
    org.springframework.scheduling: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# 任务调度配置
job:
  like-notify:
    # 定时任务配置
    cron: "0 0 2 * * ?"  # 每天凌晨2点执行
    # 批量处理配置
    batch-size: 200
    max-batch-size: 500
    min-batch-size: 100
    # 并发配置
    concurrent-threads: 1
    # 重试配置
    max-retry-times: 3
    retry-delay-ms: 3000
    # 内存管理配置
    memory-threshold: 800MB
    memory-check-interval: 20

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 