# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0

logging:
  level:
    com.hidreamai.community: DEBUG
    org.springframework.scheduling: DEBUG
    org.springframework.web: DEBUG

# 开发环境任务配置
job:
  like-notify:
    # 开发环境可以更频繁地执行
    cron: "0 */30 * * * ?"  # 每30分钟执行一次
    batch-size: 100  # 开发环境使用更小的批次
    max-batch-size: 200
    min-batch-size: 50 